// Result post-processing engine.
// Prefers the Rust → WebAssembly build in /public/engine (produced by wasm-pack
// in CI). Falls back to an equivalent TypeScript implementation so the app
// works identically when the WASM artifact is absent (e.g. local dev without
// a Rust toolchain).

export interface Segment {
  text: string;
  mark: boolean;
}

export interface UiResult {
  id: string;
  title: Segment[];
  url: string;
  display: string;
  host: string;
  date: string | null;
  snippet: Segment[];
  score: number;
}

export interface ApiResult {
  id: string | null;
  name: string | null;
  url: string;
  displayUrl: string | null;
  snippet: string | null;
  summary: string | null;
  datePublished: string | null;
}

export interface Processed {
  results: UiResult[];
  engine: "wasm" | "js";
  ms: number;
}

interface WasmEngine {
  default: (input?: unknown) => Promise<unknown>;
  process_results: (query: string, now_ms: number, raw_json: string) => string;
}

// Runtime URL — the artifact is generated by wasm-pack into public/engine.
const ENGINE_URL = "/engine/search_core.js";

const MAX_RESULTS = 10;
const MAX_PER_HOST = 3;
const SNIPPET_LIMIT = 320;
const DISPLAY_LIMIT = 72;

let enginePromise: Promise<WasmEngine | null> | null = null;

function loadEngine(): Promise<WasmEngine | null> {
  enginePromise ??= (async () => {
    try {
      const mod = (await import(/* @vite-ignore */ ENGINE_URL)) as WasmEngine;
      await mod.default();
      return mod;
    } catch {
      return null;
    }
  })();
  return enginePromise;
}

// Warm the engine in idle time so the first search hits a hot path.
if (typeof requestIdleCallback === "function") {
  requestIdleCallback(() => void loadEngine());
} else {
  setTimeout(() => void loadEngine(), 1500);
}

export function cleanQuery(input: string): string {
  return input.trim().replace(/\s+/g, " ").slice(0, 300);
}

export async function processResults(query: string, apiResults: ApiResult[]): Promise<Processed> {
  const t0 = performance.now();
  const wasm = await loadEngine();
  if (wasm) {
    try {
      const out = wasm.process_results(query, Date.now(), JSON.stringify(apiResults));
      const parsed = JSON.parse(out) as { results: UiResult[] };
      return { results: parsed.results, engine: "wasm", ms: performance.now() - t0 };
    } catch {
      // fall through to the JS implementation
    }
  }
  return { results: jsProcess(query, apiResults), engine: "js", ms: performance.now() - t0 };
}

// ---- TypeScript fallback (mirrors crates/search-core) ----

function jsProcess(query: string, raw: ApiResult[]): UiResult[] {
  const terms = queryTerms(query);
  const seen = new Set<string>();
  const perHost = new Map<string, number>();
  const scored: Array<{ idx: number; score: number; r: UiResult }> = [];

  raw.forEach((r, idx) => {
    if (!r.url) return;
    const host = hostOf(r.url);
    const key = dedupeKey(r.url);
    if (seen.has(key)) return;
    seen.add(key);
    const n = perHost.get(host) ?? 0;
    if (n >= MAX_PER_HOST) return;
    perHost.set(host, n + 1);

    const title = (r.name ?? "").trim() || host;
    const body = (r.snippet ?? r.summary ?? "").trim();
    const score = rankScore(idx, title, body, r.url, terms, !!r.datePublished);

    scored.push({
      idx,
      score,
      r: {
        id: r.id ?? `r${idx}`,
        title: markSegments(truncate(title, 140), terms),
        url: r.url,
        display: (r.displayUrl ?? "").replace(/\/$/, "") || truncate(displayOf(r.url), DISPLAY_LIMIT),
        host,
        date: r.datePublished ? dateLabel(Date.now(), r.datePublished) : null,
        snippet: markSegments(truncate(body, SNIPPET_LIMIT), terms),
        score,
      },
    });
  });

  scored.sort((a, b) => b.score - a.score || a.idx - b.idx);
  return scored.slice(0, MAX_RESULTS).map((s) => s.r);
}

function queryTerms(query: string): string[] {
  const terms = [...new Set(query.toLowerCase().split(/[^\p{L}\p{N}]+/u).filter((t) => t.length >= 2))];
  return terms.sort((a, b) => b.length - a.length);
}

function hostOf(url: string): string {
  const rest = url.split("://")[1] ?? url;
  return (rest.split("/")[0] ?? rest).replace(/^www\./, "").toLowerCase();
}

function dedupeKey(url: string): string {
  const rest = url.split("://")[1] ?? url;
  return rest.replace(/^www\./, "").replace(/\/$/, "").split("#")[0].toLowerCase();
}

function displayOf(url: string): string {
  const rest = url.split("://")[1] ?? url;
  return rest.replace(/\/$/, "");
}

function rankScore(idx: number, title: string, body: string, url: string, terms: string[], hasDate: boolean): number {
  let score = 1 / (1 + idx * 0.12);
  if (terms.length) {
    const tl = title.toLowerCase();
    const bl = body.toLowerCase();
    const inTitle = terms.filter((t) => tl.includes(t)).length;
    const inBody = terms.filter((t) => bl.includes(t)).length;
    score += (0.4 * inTitle) / terms.length + (0.15 * inBody) / terms.length;
  }
  if (url.startsWith("https://")) score += 0.03;
  if (hasDate) score += 0.04;
  return score;
}

function markSegments(text: string, terms: string[]): Segment[] {
  if (!terms.length || !text) return [{ text, mark: false }];
  const lower = text.toLowerCase();
  const ranges: Array<[number, number]> = [];
  for (const t of terms) {
    let start = 0;
    while (start + t.length <= lower.length) {
      const pos = lower.indexOf(t, start);
      if (pos < 0) break;
      ranges.push([pos, pos + t.length]);
      start = pos + t.length;
    }
  }
  ranges.sort((a, b) => a[0] - b[0]);
  const merged: Array<[number, number]> = [];
  for (const [s, e] of ranges) {
    const last = merged[merged.length - 1];
    if (last && s <= last[1]) last[1] = Math.max(last[1], e);
    else merged.push([s, e]);
  }
  const out: Segment[] = [];
  let cursor = 0;
  for (const [s, e] of merged) {
    if (s < cursor) continue;
    if (s > cursor) out.push({ text: text.slice(cursor, s), mark: false });
    out.push({ text: text.slice(s, e), mark: true });
    cursor = e;
  }
  if (cursor < text.length) out.push({ text: text.slice(cursor), mark: false });
  return out.length ? out : [{ text, mark: false }];
}

function truncate(s: string, max: number): string {
  return s.length > max ? s.slice(0, max).trimEnd() + "…" : s;
}

function dateLabel(nowMs: number, date: string): string | null {
  const m = /^(\d{4})-(\d{2})-(\d{2})/.exec(date);
  if (!m) return null;
  const then = Date.UTC(+m[1], +m[2] - 1, +m[3]);
  const diff = Math.floor(nowMs / 86400000) - Math.floor(then / 86400000);
  if (diff <= 0) return "Today";
  if (diff === 1) return "Yesterday";
  if (diff < 7) return `${diff} days ago`;
  if (diff < 30) {
    const w = Math.floor(diff / 7);
    return w === 1 ? "1 week ago" : `${w} weeks ago`;
  }
  if (diff < 365) {
    const mo = Math.floor(diff / 30);
    return mo === 1 ? "1 month ago" : `${mo} months ago`;
  }
  const yr = Math.floor(diff / 365);
  return yr === 1 ? "1 year ago" : `${yr} years ago`;
}
